FROM oven/bun:1.1-alpine AS dev

WORKDIR /app

COPY package.json bun.lock* ./

RUN bun install --frozen-lockfile

COPY . .

ENV WATCHPACK_POLLING=true
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["bun", "run", "dev"]
