services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: .
    command: python -B -m uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stock_data
    depends_on:
      - db

  frontend:
    build: .
    command: python -B -m streamlit run app.py --server.port 8501 --server.headless true --server.address 0.0.0.0
    working_dir: /app/frontend
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/stock_data
    depends_on:
      - backend

volumes:
  pgdata:
